### ISSUE TITLE
Getting started - 404 

### ISSUE THREAD

**Issue by billaul** [LesliTech/Lesli#39]
All link under `Getting started` on https://www.lesli.dev/engines/lesli/getting-started/ render a 404

**Comment by ldonis** [comment]
Hello @billaul,
Thank you for reporting this issue. The links under the "Getting Started" section are now working correctly :)  [https://www.lesli.dev/engines/lesli/getting-started/](https://www.lesli.dev/engines/lesli/getting-started/)
